const graphsData = [
  { id: 'bellCurve1', title: 'Honesty-Humility', value: 3.39, group: 'domain' },
  { id: 'bellCurve2', title: 'Emotionality', value: 2.62, group: 'domain' },
  { id: 'bellCurve5', title: 'Extraversion', value: 6.66, group: 'domain' },
  { id: 'bellCurve3', title: 'Agreeableness', value: 4.28, group: 'domain' },
  { id: 'bellCurve4', title: 'Conscientiousness', value: 4.59, group: 'domain' },
  { id: 'bellCurve6', title: 'Openness to Experience', value: 7.63, group: 'domain' },
  { id: 'bellCurve7', title: 'Honesty-Humility: Sincerity', value: 2.81, group: 'facet', domain: 'honesty' },
  { id: 'bellCurve8', title: 'Honesty-Humility: Fairness', value: 3.55, group: 'facet', domain: 'honesty' },
  { id: 'bellCurve9', title: 'Honesty-Humility: Greed Avoidance', value: 6.12, group: 'facet', domain: 'honesty' },
  { id: 'bellCurve10', title: 'Honesty-Humility: Modesty', value: 2.6, group: 'facet', domain: 'honesty' },
  { id: 'bellCurve11', title: 'Emotionality: Fearfulness', value: 3.42, group: 'facet', domain: 'emotionality' },
  { id: 'bellCurve12', title: 'Emotionality: Anxiety', value: 2.87, group: 'facet', domain: 'emotionality' },
  { id: 'bellCurve13', title: 'Emotionality: Dependence', value: 2.4, group: 'facet', domain: 'emotionality' },
  { id: 'bellCurve14', title: 'Emotionality: Sentimentality', value: 5.04, group: 'facet', domain: 'emotionality' },
  { id: 'bellCurve15', title: 'Extraversion: Social Self-Esteem', value: 6.74, group: 'facet', domain: 'extraversion' },
  { id: 'bellCurve16', title: 'Extraversion: Social Boldness', value: 7.29, group: 'facet', domain: 'extraversion' },
  { id: 'bellCurve17', title: 'Extraversion: Sociability', value: 5.88, group: 'facet', domain: 'extraversion' },
  { id: 'bellCurve18', title: 'Extraversion: Liveliness', value: 4.98, group: 'facet', domain: 'extraversion' },
  { id: 'bellCurve19', title: 'Agreeableness: Forgivingness', value: 4.07, group: 'facet', domain: 'agreeableness' },
  { id: 'bellCurve20', title: 'Agreeableness: Gentleness', value: 3.32, group: 'facet', domain: 'agreeableness' },
  { id: 'bellCurve21', title: 'Agreeableness: Flexibility', value: 6.3, group: 'facet', domain: 'agreeableness' },
  { id: 'bellCurve22', title: 'Agreeableness: Patience', value: 4.24, group: 'facet', domain: 'agreeableness' },
  { id: 'bellCurve23', title: 'Conscientiousness: Organization', value: 3.64, group: 'facet', domain: 'conscientiousness' },
  { id: 'bellCurve24', title: 'Conscientiousness: Diligence', value: 5.34, group: 'facet', domain: 'conscientiousness' },
  { id: 'bellCurve25', title: 'Conscientiousness: Perfectionism', value: 6.96, group: 'facet', domain: 'conscientiousness' },
  { id: 'bellCurve26', title: 'Conscientiousness: Prudence', value: 3.07, group: 'facet', domain: 'conscientiousness' },
  { id: 'bellCurve27', title: 'Openness to Experience: Aesthetic Appreciation', value: 6.71, group: 'facet', domain: 'openness' },
  { id: 'bellCurve28', title: 'Openness to Experience: Inquisitiveness', value: 7.09, group: 'facet', domain: 'openness' },
  { id: 'bellCurve29', title: 'Openness to Experience: Creativity', value: 6.65, group: 'facet', domain: 'openness' },
  { id: 'bellCurve30', title: 'Openness to Experience: Unconventionality', value: 7.43, group: 'facet', domain: 'openness' },
  { id: 'bellCurve31', title: 'Interstitial Scale: Altruism', value: 4.1, group: 'interstitial' },
];
